# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place,
# they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess,
# tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout the game and tell the user at the end.
import random

class TheGame:
    def cows_AndBulls(self, user_guess):
        win_flag, cow, bull = 0, 0, 0
        guess_list = []
        genNum_list = []
        gen_num = random.randint(1000,9999)
        print("Number Generated by system : ", gen_num)
        temp_guess = user_guess
        temp_genNum = gen_num
        if user_guess not in range(1000, 9999) : print("Please enter 4 digit number only!")   #Verify Correct numerical entry
        else :
            for i in range(4):
                guess_list.append(temp_guess % 10)    # convert guess number into a list
                temp_guess = temp_guess // 10
                genNum_list.append(temp_genNum % 10)     # convert generated number into a list
                temp_genNum = temp_genNum // 10

            for itr in range(4):
                if guess_list[itr] == genNum_list[itr] : cow = cow + 1    # digit that the user guessed correctly in the correct place of generated number
                elif guess_list[itr] in genNum_list and itr != genNum_list.index(guess_list[itr]):
                    bull = bull + 1         # digit that the user guessed correctly in the wrong place of generated number

            print("Your ScoreCard -->")   # Collection of Cows and Bulls
            print("Cows : ", cow)
            print("Bulls : ", bull)

            if cow == 4:
                print("Congratulations! You win!!")
            else:
                self.cows_AndBulls(int(input("Please Re-enter 4 digit number : ")))      # Repeat the game until the User wins

obj = TheGame()
num = int(input("Please Enter 4 digit number : "))
obj.cows_AndBulls(num)
